services:
  formulae-mirror:
    image: quay.io/amrkmn/formulae-mirror:latest
    container_name: formulae-mirror
    environment:
      - TRUSTED_PROXIES=
    ports:
      - 8080:80
    volumes:
      - nginx-cache:/var/cache/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  nginx-cache:
